### ISSUE TITLE
"TopDown: 'ViT is not in the models registry'"

### ISSUE THREAD

**Issue by yyvhang** [IDEA-Research/OSX#1]
When I run demo.py, there seems a bug: "TopDown: 'ViT is not in the models registry'". I have run setup.py in main/transformer_utils and my mmpose version is 0.29.0. Hope to get your reply.

**Comment by linjing7** [comment]
@yyvhang Hi, did you install it by running `python setup.py develop?

**Comment by yyvhang** [comment]
yeah, I have done this step, but still exist this bug

**Comment by linjing7** [comment]
Hi, I'm sorry that the mmcv-full version in the requirements.txt is incorrect. Please install mmcv-full by: 
```
pip install openmim
mim install mmcv-full==1.7.1
```
and then install the mmpose again. Feel free to tell me if you have any other problems.

**Comment by yyvhang** [comment]
> @yyvhang Hi, I'm sorry that the mmcv-full version in the requirements.txt is incorrect. Please install mmcv-full by:
> 
> ```
> pip install openmim
> mim install mmcv-full==1.7.1
> ```
> 
> and then install the mmpose again. Feel free to tell me if you have any other problems.

it works for me, thanks

**Comment by herochen7372** [comment]
Hi，thank you for your help. Now I have a new problem.

detector = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
Exception has occurred: RemoteDisconnected
Remote end closed connection without response

**Comment by linjing7** [comment]
@herochen7372 Hi, please refer to this [issue](https://github.com/IDEA-Research/OSX/issues/65).

**Comment by herochen7372** [comment]
Thank you，bro.
