### ISSUE TITLE
run test error

### ISSUE THREAD

**Issue by Followmeczx** [IDEA-Research/OSX#100]
I train model with run
`python train.py --gpu 1 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16`
And I want to test，so I run
` python test.py --gpu 2 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset EHF`
But it report error
`loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Traceback (most recent call last):
  File "/data/OSX/main/test.py", line 73, in <module>
    main()
  File "/data/OSX/main/test.py", line 46, in main
    tester._make_model()
  File "/data/OSX/main/../common/base.py", line 189, in _make_model
    model.load_state_dict(new_state_dict, strict=False)
  File "/data/.conda/envs/OSX/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.face_regressor.expr_out.0.weight: copying a param with shape torch.Size([10, 37592]) from checkpoint, the shape in current model is torch.Size([10, 1024]).
	size mismatch for module.face_regressor.jaw_pose_out.0.weight: copying a param with shape torch.Size([6, 37592]) from checkpoint, the shape in current model is torch.Size([6, 1024]).
`

**Comment by MilkLoo** [comment]
May I ask, how did you solve this problem？

**Comment by Followmeczx** [comment]
> May I ask, how did you solve this problem？

In test.py
![image](https://github.com/IDEA-Research/OSX/assets/65723649/b977e0d6-3160-4996-8820-8a84815c7e76)
decoder_setting default = 'wo_face_decoder'
I changed it to `default = normal`. Because In train.py 
![image](https://github.com/IDEA-Research/OSX/assets/65723649/3829ff5f-0e7e-4d32-8e4c-ef0d272772c4)
decoder_setting default='normal'

**Comment by MilkLoo** [comment]
Think you！I have one more question. I want to train on the server, but these data sets are too large, the server disk storage is not enough, only 512GB, is there any good training method or strategy?

**Comment by Followmeczx** [comment]
> Think you！I have one more question. I want to train on the server, but these data sets are too large, the server disk storage is not enough, only 512GB, is there any good training method or strategy?

I don't have a good idea. I have enough space on my server, but I didn't download AGORA's 3840*2160 dataset because it's too big almost 300G!

**Comment by MilkLoo** [comment]
Thank you for your answer！
