### ISSUE TITLE
KeyError: 'pa_mpvpe_all'

### ISSUE THREAD

**Issue by Followmeczx** [IDEA-Research/OSX#101]
I have only downloaded AGORA data in 1280x720 resolution, and I have downloaded the AGORA_train.json, AGORA_validation.json, and AGORA_test_bbox.json files. Therefore, the AGORA folder in the dataset folder is not empty, and it follows the path you mentioned, which is `dataset/AGORA/data/1280x720`. 
After I trained a model , I was able to get test results on EHF. However, when I run the command you provided `python test.py --gpu 2 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset AGORA`, I encountered an error showing `KeyError: 'pa_mpvpe_all'`. 
Can you provide some assistance?

**Comment by linjing7** [comment]
I think this is because you have not correctly prepared the AGORA dataset, and the number of AGORA test set is zero.

**Comment by Followmeczx** [comment]
you mean I also need to download 3840x2160 data?

**Comment by linjing7** [comment]
After downloading the datasets, you should follow the [README.md](https://github.com/IDEA-Research/OSX/blob/main/tool/AGORA/README.md) to process them into the required formats.

**Comment by Followmeczx** [comment]
I have a few questions regarding the AGORA readme. First, are the steps 'Cleaning SMPL parameters' and 'Make annotation files' necessary? This is because the formats mentioned in the AGORA dataset of the OSX project's readme do not include 'gt_joints_2d', 'gt_joints_3d', and 'gt_verts'.
<img width="287" alt="image" src="https://github.com/IDEA-Research/OSX/assets/65723649/d975f6d0-c4fe-462b-b88f-b2dff4697ef5">
 Additionally, I can directly download the files 'AGORA_train.json', 'AGORA_validation.json', and 'AGORA_test_bbox.json' from the provided links without going through the mentioned processing steps. 
<img width="389" alt="image" src="https://github.com/IDEA-Research/OSX/assets/65723649/c9ced4b4-4bd1-40b1-b95c-8e9b5c57d6b7">
<img width="910" alt="image" src="https://github.com/IDEA-Research/OSX/assets/65723649/93334476-356b-4cd0-9923-2dad264d12b3">
Second, in the 'Cleaning SMPL parameters' step, you mentioned running 'tensor_to_numpy_parameter.py', but the file available is 'tensor_to_numpy_smpl_parameter.py'. Does it only process 'smpl_gt', and is there no need to process the 'smplx_gt' file?
<img width="876" alt="image" src="https://github.com/IDEA-Research/OSX/assets/65723649/91174992-e2a4-4115-9d6d-8f4106deb66b">
I follow the README.md of OSX :
-- AGORA
|   |   |-- data
|   |   |   |-- AGORA_train.json
|   |   |   |-- AGORA_validation.json
|   |   |   |-- AGORA_test_bbox.json
|   |   |   |-- 1280x720
I don't know if that's right.

**Comment by Followmeczx** [comment]
Hi, when I run agora2coco.py to make a comment file for AGORA, I get the following error. I don't know what the problem is, can you help me? Thanks a lot!
![image](https://github.com/IDEA-Research/OSX/assets/65723649/896e4bc2-fac7-4626-8cd8-64eff58af7d0)
This is because points_2d = np.array(data_smplx['gt_joints_2d'][i][j]).reshape(-1,2) The processed size is (45, 2)

**Comment by Followmeczx** [comment]
Thank you. I solved this proeblem. Because I only download 1280x720 dataset, I need change `self.resolution = (720, 1280)` in AGORA.py.
