### ISSUE TITLE
Rendering 2D keypoints onto the original input image

### ISSUE THREAD

**Issue by paulpanwang** [IDEA-Research/OSX#102]
I have a question regarding rendering 2D keypoints onto the original input image and rotating reconstructed keypoints. I would like to know how to achieve these two tasks. Specifically, I would like to understand the process of rendering 2D keypoints onto the original input image and also how to rotate the reconstructed keypoints.

Could you please provide guidance or code examples on how to render 2D keypoints onto the original input image? Additionally, I would appreciate instructions on how to rotate the reconstructed keypoints.

Thank you in advance for your assistance!

**Comment by linjing7** [comment]
Hi, to visualize the 2D keypoints onto the original image, please refer to this [issue](https://github.com/IDEA-Research/OSX/issues/23). To rotate the keypoints, you could multiply the 3d keypoints by a rotation matrix before projection.

**Comment by paulpanwang** [comment]
Thank you for your response. We have successfully rendered the 2D keypoints. I have another important question: Do you have any code/instructions for connecting the 2D keypoints? I greatly appreciate your help.

**Comment by linjing7** [comment]
Hi, please refer to this [function](https://github.com/IDEA-Research/OSX/blob/118cf97fb1f144930bf93d88794b525d579b2d0c/common/utils/vis.py#L13).

**Comment by paulpanwang** [comment]
But I couldn't find the kps_lines parameter defined in **vis_keypoints_with_skeleton** funcation throughout the repository. Could you please help me by providing the kps_lines parameter? Thanks.

**Comment by linjing7** [comment]
Hi, you can define the skeleton by yourself, here is an example for SMPL skeleton:
```
def get_smpl_skeleton():
    return np.array(
        [
            [ 0, 1 ],
            [ 0, 2 ],
            [ 0, 3 ],
            [ 1, 4 ],
            [ 2, 5 ],
            [ 3, 6 ],
            [ 4, 7 ],
            [ 5, 8 ],
            [ 6, 9 ],
            [ 7, 10],
            [ 8, 11],
            [ 9, 12],
            [ 9, 13],
            [ 9, 14],
            [12, 15],
            [13, 16],
            [14, 17],
            [16, 18],
            [17, 19],
            [18, 20],
            [19, 21]
        ]
    )
```
