### ISSUE TITLE
Missing File for SMPL_python_v.1.0.0.zip

### ISSUE THREAD

**Issue by jiiiisoo** [IDEA-Research/OSX#103]
Hello, thanks for the great work.

I want to download [SMPL_python_v.1.0.0.zip](https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip) but it seems that the link is not available.

Could you provide this file?

My email is [jisoo6687@yonsei.ac.kr](mailto:jisoo6687@yonsei.ac.kr)
Or is it okay to use SMPL_python_v.1.1.0.zip ?

Thanks!

**Comment by linjing7** [comment]
Yes, I think it's okay to use SMPL_python_v.1.1.0.zip.

**Comment by jiiiisoo** [comment]
I think it's available now. Thank you for your response !
