### ISSUE TITLE
Where's the smpl["trans"] parameter from the output results?

### ISSUE THREAD

**Issue by jackieyung** [IDEA-Research/OSX#104]
@linjing7 Thanks for your sharing of the amazing method. 

I have a question about the output from the code. I need the gloal translation of the predicted person, like the smpl['trans'] parameter, but I couldn't find it from your definition ( see the screenshot image ). Could you give me an advice how to get this parameter? Thanks a lot.

![image](https://github.com/IDEA-Research/OSX/assets/13002561/c87216ab-91f8-41e2-92d2-c0743f0c4ff0)

**Comment by linjing7** [comment]
out['cam_trans']
