### ISSUE TITLE
 ssh environment without install these libs

### ISSUE THREAD

**Issue by tvshow5727** [IDEA-Research/OSX#107]
![image](https://github.com/IDEA-Research/OSX/assets/31235096/53babd62-96ac-43f0-89bd-a45090d819d8)
i run the demo.py ,Is the content in the above picture mandatory to install？
i am not install these; run the demo.py successfully ,the rendered demo.jpg is saved ,but the rendered result is abnormal...Is the abnormal result related to the uninstalled content？

**Comment by linjing7** [comment]
No, I think there is something wrong with the model. Have you successfully loaded the pretrained model? Can you show your results?
