### ISSUE TITLE
Question about definition of Original setup and Share Backbone

### ISSUE THREAD

**Issue by chojinie** [IDEA-Research/OSX#110]
Hello It's very beatiful work. Thank you for share nice work.

I have some question in paper.

Where Methodology part, maybe page 4. There are part of Motivation that describe Table2 show preliminary experiments. And It is described Original setup and Shared backbone setup. But i don't understand well.

Did Ori. setup mean hand4whole method? (In the hand4whole paper's architecture, I understand it use 4 ResNet to Backbone)
What is the shared backbone..? which means that feature extract backbone is unified for just One ResNET? just like, When image feed input to backbone(one resnet) and estimate all components contains hand, face, body?

And could you know me how can I construct Share Backbone?  Because i wanna implement and try to follow your way.

**Comment by linjing7** [comment]
Hi, thanks for your interest! Yes, the Ori. setup mean hand4whole. The shared backbone means that we extract the body/hand/face feature using the same ResNet.

**Comment by chojinie** [comment]
@linjing7  Thank you for the quick and accurate answer!
