### ISSUE TITLE
What is meaning "wo_decoder"

### ISSUE THREAD

**Issue by chojinie** [IDEA-Research/OSX#113]
Hi, I'm jin.

I'm curious about expression of pretrained models.

About, osx_l_wo_decoder.pth.tar
It seems that I haven't found the answer I was looking for in response #19... Does the file named "osx_l_wo_decoder.pth.tar" refer to a model trained without the decoder on the OSX model, which has been pretrained on the MPII, MSCOCO-Wholebody, and H36M datasets, and further trained on the U-body dataset?

And could you please, why this result be made? I just tried demo.py with arbitraty data from Upper body data set

original image is here,
![image](https://github.com/IDEA-Research/OSX/assets/106041887/4ce86940-2cf9-419a-bf74-1ce593ab3151)

and, with this command, result is good. 
python demo.py --gpu 0 --img_path /workspace/jin/OSX/dataset/UBody/images/Singing/Singing_S1_Trim2/Singing_S1_Trim2_scene003/000020.png --output_folder /workspace/jin/OSX/demo --decoder_setting wo_decoder --pretrained_model_path /workspace/jin/OSX/pretrained_models/osx_l_wo_decoder.pth.tar

![image](https://github.com/IDEA-Research/OSX/assets/106041887/3aadfd2b-c7b8-43cc-b554-fcb1b12c6c22)

but, i change the command  with this , result was bad..
python demo.py --gpu 0 --img_path /workspace/jin/OSX/dataset/UBody/images/Singing/Singing_S1_Trim2/Singing_S1_Trim2_scene003/000020.png --output_folder /workspace/jin/OSX/demo --decoder_setting wo_decoder --pretrained_model_path /workspace/jin/OSX/pretrained_models/osx_l_agora.pth.tar 

![image](https://github.com/IDEA-Research/OSX/assets/106041887/db24c599-96f1-4cf4-9861-a03aa65e738d)

I found that i use command with " --decoder _setting wo_decoder" even use pretrained model "osx_l_agora.pth.tar"     i anticipated that, with agora pretrained model. gonna be upgraded result. but result is worse than before.

**Comment by linjing7** [comment]
Hi, there exists a domain gap between AGORA dataset and in-the-wild images. `osx_l_agora.pth.tar` is fine-tuned on AGORA dataset and thus could not perform well on the in-the-wild images.

**Comment by chojinie** [comment]
I'm sorry. I think I read about this in a paper, but I missed it and asked again.

And Last year, Max Planck released BEDLAM(https://bedlam.is.tue.mpg.de/). Have you tested with that dataset? The paper presents research results that training with the synthetic dataset called BEDLAM also results in improved performance when tested on in-the-wild data.

**Comment by linjing7** [comment]
Hi, the `wo_decoder` setting is not the same as the architecture in paper. Instead, we regress the hand and face params based on the encoder feature.

**Comment by chojinie** [comment]
@linjing7 Thanks! i just guessed but not for sure. And with your reply, i have a confidence to understand!
