### ISSUE TITLE
about image token

### ISSUE THREAD

**Issue by Followmeczx** [IDEA-Research/OSX#115]
`img_feat, task_tokens = self.encoder(body_img)  # task_tokens:[bs, N, c]`
`shape_token, cam_token, expr_token, jaw_pose_token, hand_token, body_pose_token = \ task_tokens[:, 0], task_tokens[:, 1], task_tokens[:, 2], task_tokens[:, 3], task_tokens[:, 4:6], task_tokens[:, 6:]`
Can you give me some answers as to why we can get the corresponding token directly like this

**Comment by linjing7** [comment]
We assign a token for each param and then regress the param based on the token. Please refer to the method part of the paper.
