### ISSUE TITLE
Results Mismatch compare paper's(?) on Trainig setting 3 and test setting 3

### ISSUE THREAD

**Issue by chojinie** [IDEA-Research/OSX#116]
Hi, @linjing7

I bring some result from guiding instruction on paper and github pages.
I have some question about that.

1. Followed by github's guide like setting 3(Train on MSCOCO, Human3.6m, MPII, UBody-Train and Test on UBody-val) : 
[Train] It took a 60hours by A60002way(64G*2) gpu:0,1 / Command : python train.py --gpu 0,1 --lr 1e-4 --exp_name output/train_setting3 --train_batch_size 16  --ubody_benchmark --decoder_setting wo_decoder

--> I got snapshot_13.pth.tar

[Test] Same Hardware / Command : python test.py --gpu 0,1,2,3 --exp_name output/train_setting3/ --pretrained_model_path ../output/train_setting3/model_dump/snapshot_13.pth --testset UBody --test_batch_size 64 --decoder_setting wo_decoder

--> Then I got result 
![image](https://github.com/IDEA-Research/OSX/assets/106041887/f96133f7-e063-414f-b4fd-6ac8021da89d)

and Paper's result just like that
![image](https://github.com/IDEA-Research/OSX/assets/106041887/1569dbad-4d4b-4496-a1f5-76300976f7b1)

It seems very different, even setting3 result is better than paper's result.

Does this event is right? then why? I'm merely speculating that the difference in performance arises from whether osx_l was fine-tuned with the U-body dataset or initially trained from scratch including the U-body dataset.

2. Followed by github's Testing OSX guideline,
I test the model with command 
python test.py --gpu 0,1 --exp_name /output/test_setting3  --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar --testset UBody --test_batch_size 64 --decoder_setting wo_decoder

--> I got this result
![image](https://github.com/IDEA-Research/OSX/assets/106041887/531fffe1-8afe-4fab-a553-71d411f1a8e0)

It is more near the result of paper's.
In testing OSX, they use the pretrained model osx_l.pth.tar for testing. Is this the experimental approach referred to in Table 5 of the paper? And is this osx_l.pth.tar a model that was pretrained on existing datasets (MPII, H36M, MSCOCO-Wholebody) and then fine-tuned on the U-body dataset?
However, since this is a without decoder model, the performance is slightly lower than what is presented in the paper, right?

**Comment by linjing7** [comment]
Hi, thanks for your interest! Yes, the result of Table 5 refers to the osx_l.pth.tar model that pretrained on existing datasets and fine-tuned on the UBody trainset. I'm happy that you can achieve a better result than our paper by designing a better training scheme.

**Comment by chojinie** [comment]
Thanks for rapid and accurate reply!!

I have another questions about correlation of setting with performance.

In my command "[Train] It took a 60hours by A60002way(64G*2) gpu:0,1 / Command : python train.py --gpu 0,1 --lr 1e-4 --exp_name output/train_setting3 --train_batch_size 16 --ubody_benchmark --decoder_setting wo_decoder" 

The only difference between the command I used and setting3 command you provided is that I used A6000 GPUs (with a memory capacity of 64GB) and utilizes two GPUs.

**Comment by linjing7** [comment]
Okay, it seems that there do exist significant differences between your setting and the original setting. But I'm pleased that you could achieve a better performance than our paper :)

**Comment by chojinie** [comment]
Thanks!!

**Comment by chojinie** [comment]
Hi @linjing7.
I'm Jin.

I reopen issue to clarify the problem.

It seems like an extension of what we discussed earlier. I followed the Training Setting 3 protocol, with the only differences being that I used only two GPUs and my GPUs are A6000s.

I used the following command:
python train.py --gpu 0,1 --lr 1e-4 --exp_name output/train_setting3 --train_batch_size 16 --ubody_benchmark --decoder_setting wo_decoder

And, inspecting train.py, it appears that osx_l.pth.tar is added by default as the pretrained_model_path.

![image](https://github.com/IDEA-Research/OSX/assets/106041887/41c05ac9-dbdf-4940-b360-aa84c51f861f)

and my train_log, you can see. it took a pretrained_model/osx_l.pth.tar
![image](https://github.com/IDEA-Research/OSX/assets/106041887/23838ec5-d866-435f-979b-144a31aadcde)


I consider this training setting 3 is about SCRATCH training with ViT model(osx_vit_l.pth) But, according to the images above it does not. Was I wrong in my thinking?

**Comment by linjing7** [comment]
Yes, `pretrained_model_path` is not activated. Only the backbone pretrained model is loaded [here](https://github.com/IDEA-Research/OSX/blob/118cf97fb1f144930bf93d88794b525d579b2d0c/main/OSX_WoDecoder.py#L379).

**Comment by chojinie** [comment]
Thanks for timey reply!
