### ISSUE TITLE
[Question] About Human detector

### ISSUE THREAD

**Issue by chojinie** [IDEA-Research/OSX#118]
Hi @linjing7 .
I'm Jin.

Thank you for always providing kind responses. I have two questions.

(1) As far as I know, in the field of single-person mesh recovery like OSX, it seems that cropped images of individuals are used as inputs to the model. So, it would seem necessary to use a human detector, but I couldn't find anything like that in your code. Instead, in the demo.py file, it's evident that yolov5 is being used.

I might have missed something in the paper or the code regarding the human detector, but could you explain how OSX identifies humans from the dataset during model training?

(2) Furthermore, until now, I had believed that methods following this TOP-DOWN approach involve locating keypoints and estimating meshes within the human bounding box, leading to a considerable reliance on human detectors. Am I correct in assuming this?

**Comment by linjing7** [comment]
Hi, thanks for your interest! Yes, we need a human detector to detect the human bbox. 
(1) For the dataset during training, we use the GT bbox and have cropped it in the data loader. 
(2) Yes, the detection accuracy will influence the performance, especially for some challenging cases in AGORA. Some human detectors could not detect all the persons within an image, leading to a low NMJE.
