### ISSUE TITLE
When I making annotation files, I encountered the following error. 

### ISSUE THREAD

**Issue by Ruaabick** [IDEA-Research/OSX#15]
When I making annotation files, I encountered the following error. 

Traceback (most recent call last):
  File "agora2coco.py", line 63, in <module>
    smplx_layer = smplx.create(args.human_model_path, 'smplx', use_pca=False)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 2404, in create
    return SMPLX(model_path, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 969, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(
AssertionError: Path /data/OSX/dataset/AGORA/data/smplx does not exist!

So I download and unzip [models_smplx_v1_1.zip](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip),It reported the following error.

Traceback (most recent call last):
  File "agora2coco.py", line 149, in <module>
    joints_2d_lhand = joints_2d[smplx_joint_part['lhand'],:]
IndexError: index 66 is out of bounds for axis 0 with size 45

What files should I place under the human model layer path?

**Comment by linjing7** [comment]
Hi, you need to collect the human model files like the following structure:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/70081899/232319291-859bed48-a01a-4f88-bd82-509c91bd7cd1.png">

**Comment by Ruaabick** [comment]
I collected human model files following the steps, but when I ran it again, it seems to require other files…?

```
Traceback (most recent call last):
  File "agora2coco.py", line 63, in <module>
    smplx_layer = smplx.create(args.human_model_path, 'smplx', use_pca=False)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 2404, in create
    return SMPLX(model_path, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 969, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(
AssertionError: Path /data/OSX/common/utils/human_model_files/smplx/SMPLX_NEUTRAL.npz does not exist!

```

**Comment by linjing7** [comment]
Yes, you are right, please download `SMPLX_NEUTRAL.npz` and place it into `human_model_files/smplx/` folder.

**Comment by linjing7** [comment]
It seems that the number of joints of your data `data_smplx['gt_joints_2d']` is wrong. I guess you download the SMPL-version AGORA instead of SMPLX-version.

**Comment by Ruaabick** [comment]
Sorry to bother you again. I noticed that the data_smplx variable is loaded from the train_SMPLX and validation_SMPLX in dataset_path. I downloaded the file from the [here](https://download.is.tue.mpg.de/download.php?domain=agora&resume=1&sfile=train_SMPLX.zip) and extracted it to the dataset_path directory. Did I download the wrong file? Should it be the smplx-version file?

![image](https://user-images.githubusercontent.com/55493681/232474878-0ade1f09-7c62-48d8-89d2-931b3ee8922e.png)

![image](https://user-images.githubusercontent.com/55493681/232474664-840e1c16-4585-4518-bd90-5d4110b3312c.png)

**Comment by keshuixm** [comment]
> When I making annotation files, I encountered the following error.
> 
> Traceback (most recent call last): File "agora2coco.py", line 63, in smplx_layer = smplx.create(args.human_model_path, 'smplx', use_pca=False) File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 2404, in create return SMPLX(model_path, **kwargs) File "/root/anaconda3/envs/test/lib/python3.8/site-packages/smplx/body_models.py", line 969, in **init** assert osp.exists(smplx_path), 'Path {} does not exist!'.format( AssertionError: Path /data/OSX/dataset/AGORA/data/smplx does not exist!
> 
> So I download and unzip [models_smplx_v1_1.zip](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip),It reported the following error.
> 
> Traceback (most recent call last): File "agora2coco.py", line 149, in joints_2d_lhand = joints_2d[smplx_joint_part['lhand'],:] IndexError: index 66 is out of bounds for axis 0 with size 45
> 
> What files should I place under the human model layer path?

Hello, I have encountered the same problem. Maybe, the data_smplx['gt_joints_2d'] is wrong. Have you resolved it?

**Comment by kmaksatk** [comment]
I have the same error, since you closed this issue, I was wondering if you found the solution to this.

**Comment by carlinl** [comment]
I encountered the same issue, and following the instructions above still leads me to the same problem. I would be grateful if anyone could share their solution to this!

**Comment by Followmeczx** [comment]
I found the solution, something was wrong with the code.
Load data_smplx by specifying to read the _SMPLX file
![image](https://github.com/IDEA-Research/OSX/assets/65723649/68f748bf-22b2-4fd5-893a-5a0a8d32c466)

**Comment by chojinie** [comment]
@Followmeczx Thanks! I encountered same error, and fix it.

**Comment by Charrrrrlie** [comment]
> [@carlinl](https://github.com/carlinl) I found the solution, something was wrong with the code. Load data_smplx by specifying to read the _SMPLX file ![image](https://github.com/IDEA-Research/OSX/assets/65723649/68f748bf-22b2-4fd5-893a-5a0a8d32c466)

I think there is another place that needs to be modified. `data_path_list` should be 

```
data_path_list = glob(osp.join(root_path, split + '_SMPLX', 'SMPLX', '*.pkl'))
```
or
```
data_path_list = glob(osp.join(root_path, split + '_SMPL', 'SMPL', '*.pkl'))
```

The original data_path_list leads to the dataset being processed twice.
