### ISSUE TITLE
Results of OSX

### ISSUE THREAD

**Issue by henrycjh** [IDEA-Research/OSX#16]
Hi, from the results (the same person with pink clothes, as the below imgs shown) you showed in the README.md, it seems that bigger bounding box has better results. Is the region of bounding box really matters?
![image](https://user-images.githubusercontent.com/73419275/232368985-95c48bc3-af23-441f-b3df-f13f0cdbe16c.png)

![image](https://user-images.githubusercontent.com/73419275/232369000-a028d16f-eadf-460c-bfe1-0dd7c1e3d7af.png)

**Comment by linjing7** [comment]
Hi, I don't think the size of the bounding box would obviously affect the result. The result in the second row is fitted with OSX by our annotation pipeline, while the bottom row is directly estimated by OSX.

**Comment by henrycjh** [comment]
I see. Thanks for your quick reply !
