### ISSUE TITLE
Efficiency  and infer time 

### ISSUE THREAD

**Issue by haoxurt** [IDEA-Research/OSX#17]
Thank you for your outstanding work.  In the Supplementary Material B，it is displayed that the infer time is 53ms on A100. I  wonder this time is on pytorch or tensorrt ?

**Comment by haoxurt** [comment]
Thank you for your rapid reply!   Is the graphics memory of  A100  40G or 80G?

**Comment by linjing7** [comment]
80G.

**Comment by haoxurt** [comment]
Thanks!  I got it!
