### ISSUE TITLE
Question about the 3D whole-body mesh recovery annotation.

### ISSUE THREAD

**Issue by yyvhang** [IDEA-Research/OSX#18]
Hi, I have a question about the '3D whole-body mesh recovery annotation'. As the paper(supp.) mentioned, 'we use our proposed OSX to estimate the SMPL-X parameters from human images as a proper 3D initialization'. It seems like a chicken-and-egg loop, or do you pre-train the OSX model on other datasets and then use it as an initialization for the SMPL-X parameters? I didn't find the answer in the paper, hope to get your clarification about this part, thanks a lot.

**Comment by linjing7** [comment]
Yes, you are right. We pretrain OSX on COCO, Human3.6M, and MPII and use it to generate the initial SMPL-X paramters.

**Comment by yyvhang** [comment]
> Yes, you are right. We pretrain OSX on COCO, Human3.6M, and MPII and use it to generate the initial SMPL-X paramters.

Thanks for your reply. And the opened OSX (.pth) model is trained only on the Ubody dataset, or trained by mixing all these datasets together?

**Comment by linjing7** [comment]
The released pretrained model is trained on the mixing datasets of COCO, Human3.6M, and MPII.
