### ISSUE TITLE
Question about how to get skeleton image

### ISSUE THREAD

**Issue by szm0613** [IDEA-Research/OSX#20]
Hi, sorry to bother you, I would like to ask how do I get the skeleton key-points show in original image in the demo, which can only generate the 3Dmesh of the original image?Thank you very much.

**Comment by linjing7** [comment]
Hi, we visualize the keypoints with the code of mmpose. For the 3D mesh, you can refer to [demo.py](https://github.com/IDEA-Research/OSX/blob/main/demo/demo.py) as an example.
