### ISSUE TITLE
The cam_trans jitters a lot in z-axis

### ISSUE THREAD

**Issue by henrycjh** [IDEA-Research/OSX#22]
Hi, thanks for your attention. I suppose that the cam_trans' unit is meter, and it jitters a lot in z-axis. Am I using it right? Is there a better way to predict the transitions of root joint?

**Comment by linjing7** [comment]
The value of the z-axis is related to the depth. The jitter stems from the depth ambiguity of the monocular image. I think you may try the depth estimation method to predict the depth of human and use the averaged value as the root joint depth.
