### ISSUE TITLE
demo with osx_l_wo_decoder.pth.tar ?

### ISSUE THREAD

**Issue by ZhengdiYu** [IDEA-Research/OSX#24]
Hi,

Thanks for yoru great work.

I have been trying to run demo.py with `osx_l_wo_decoder.pth.tar` because it is approximately `2 times` faster. And I just following commom/base.py to add:
```
if cfg.decoder_setting == 'normal':
    from OSX import get_model
elif cfg.decoder_setting == 'wo_face_decoder':
    from OSX_WoFaceDecoder import get_model
elif cfg.decoder_setting == 'wo_decoder':
    from OSX_WoDecoder import get_model
```
in demo.py to replace `from OSX import get_model`. And replace the the `cfg.set_additional_args(encoder_setting='osx_l', decoder_setting='normal')` into `cfg.set_additional_args(encoder_setting='osx_l', decoder_setting='wo_decoder')`.

However, the results are completely wrong even under simple cases, comparing to the original  `osx_l.pth.tar`. It seems quite strange:
![image](https://user-images.githubusercontent.com/63605407/233850991-382ecd1f-212b-45f3-b4ec-9a9a6702f9f3.png)
![image](https://user-images.githubusercontent.com/63605407/233851112-fc8859ec-31d4-49d6-be22-79973c94ca29.png)

The left-back one is using original `osx_l.pth.tar` and the front-right one is using `osx_l_wo_decoder.pth.tar`.

**Comment by linjing7** [comment]
Hi, I have supported osx_l_wo_decoder, please clone the newest code and run with: `python demo.py --gpu 0 --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar`

**Comment by ZhengdiYu** [comment]
> --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar

![image](https://user-images.githubusercontent.com/63605407/233852408-414edc1f-b370-4a9a-a50d-5c6595c2f478.png)
It throws an error

**Comment by ZhengdiYu** [comment]
> Hi, I have supported osx_l_wo_decoder, please clone the newest code and run with: `python demo.py --gpu 0 --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar`

Thanks! It works now. It seems the operations in class Demoer is necessary. It's just that the translation is not as very stable in the depth direction. But it's acceptable now.
