### ISSUE TITLE
UBody dataset generation

### ISSUE THREAD

**Issue by ZhengdiYu** [IDEA-Research/OSX#29]
Thanks for this great work!

May I ask the plan for the release of UBody dataset? In the meantime, do you also plan to release the code to annotate UBody? I have been using your code on some in-the-wild images but the results are not very precise, and I think that having a fitting pipeline described in your paper will strongly improve the performance! :)

**Comment by linjing7** [comment]
Hi, sorry for the late reply. I would release UBody during the 5.1 holidays. As for the annotation pipeline, we're keeping improve it to make it more accurate and robust, and we would consider releasing it in the future.

**Comment by ZhengdiYu** [comment]
> Hi, sorry for the late reply. I would release UBody during the 5.1 holidays. As for the annotation pipeline, we're keeping improving it to make it more accurate and robust, and we would consider releasing it in the future.

Thanks for your reply. I am reproducing the annotation pipeline. Essentially, is this based on optimizing/updating the `θ` and `β` to minimize the 2D joint loss between the `2D projection` and the `ViT-Pose's 2D prediction`, while keeping the weak-perspective camera unchanged?

**Comment by nehc0** [comment]
Hello. I'm just confirming that I should use the 'neutral' smplx model to generate mesh from the parameters of UBody dataset right?
