### ISSUE TITLE
problem about load pre_trained models 

### ISSUE THREAD

**Issue by hunting777** [IDEA-Research/OSX#30]
when i load osx_l_agora.pth.tar and osx_l_wo_decoder.pth.tar ,something went wrong . This should be a model loading problem, what configuration files do I need to modify or is the model you released different from the latest code.

Thank you for your excellent work and look forward to your reply！

size mismatch for module.body_position_net.conv.0.weight: copying a param with shape torch.Size([400, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([400, 768, 1, 1]).
        size mismatch for module.box_net.deconv.0.weight: copying a param with shape torch.Size([1424, 256, 4, 4]) from checkpoint, the shape in current model is torch.Size([1168, 256, 4, 4]).
        size mismatch for module.hand_position_net.conv.0.weight: copying a param with shape torch.Size([320, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 384, 1, 1]).
        size mismatch for module.face_regressor.expr_out.0.weight: copying a param with shape torch.Size([10, 1024]) from checkpoint, the shape in current model is torch.Size([10, 37592]).
        size mismatch for module.face_regressor.jaw_pose_out.0.weight: copying a param with shape torch.Size([6, 1024]) from checkpoint, the shape in current model is torch.Size([6, 37592]).

**Comment by keshuixm** [comment]
> when i load osx_l_agora.pth.tar and osx_l_wo_decoder.pth.tar ,something went wrong . This should be a model loading problem, what configuration files do I need to modify or is the model you released different from the latest code.
> 
> Thank you for your excellent work and look forward to your reply！
> 
> size mismatch for module.body_position_net.conv.0.weight: copying a param with shape torch.Size([400, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([400, 768, 1, 1]). size mismatch for module.box_net.deconv.0.weight: copying a param with shape torch.Size([1424, 256, 4, 4]) from checkpoint, the shape in current model is torch.Size([1168, 256, 4, 4]). size mismatch for module.hand_position_net.conv.0.weight: copying a param with shape torch.Size([320, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 384, 1, 1]). size mismatch for module.face_regressor.expr_out.0.weight: copying a param with shape torch.Size([10, 1024]) from checkpoint, the shape in current model is torch.Size([10, 37592]). size mismatch for module.face_regressor.jaw_pose_out.0.weight: copying a param with shape torch.Size([6, 1024]) from checkpoint, the shape in current model is torch.Size([6, 37592]).

Taking the liberty to disturb you, I encountered the same problem during testing, using the model trained by training code. May I ask how you resolved it?

**Comment by linjing7** [comment]
@keshuixm Hi, could you please tell me your command line?
