### ISSUE TITLE
Problem about load model

### ISSUE THREAD

**Issue by keshuixm** [IDEA-Research/OSX#31]
Hello, thank you for your excellent work! I trained and saved the snapshot_13.pth.tar using the training code you provided. But I encountered the following issues during testing:

raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.face_regressor.expr_out.0.weight: copying a param with shape torch.Size([10, 1024]) from checkpoint, the shape in current model is torch.Size([10, 37592]).
        size mismatch for module.face_regressor.jaw_pose_out.0.weight: copying a param with shape torch.Size([6, 1024]) from checkpoint, the shape in current model is torch.Size([6, 37592]).

If I have overlooked any details?

**Comment by linjing7** [comment]
@keshuixm Hi, when you test the model, you need to make sure that the `encoder_setting` and `decoder_setting` are the same as those during training. Besides, you need to specify `--pretrained_model_path` with your own pretrained model.

**Comment by keshuixm** [comment]
@linjing7  Thank you for your reply. I have successfully resolved this issue!
