### ISSUE TITLE
About the result of Ubody test

### ISSUE THREAD

**Issue by KW-NJU** [IDEA-Research/OSX#33]
To make Ubody test, I used  [video2image.py] to transform Videos into Images. Additionally, I changed "os.system(... -r 30...')" to "os.system(... -r 1...')" to make the data smaller, and run the test code with "python test.py --gpu 0,1,2,3 --exp_name output/test_setting3 --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar --testset UBody --test_batch_size 64". However, my result was quite different from yours. What should I do? And here's my running process and result:

/OSX/main/../data/UBody/UBody.py:661: RuntimeWarning: Mean of empty slice.
  np.sqrt(np.sum((mesh_out_face_align - mesh_gt_face) ** 2, 1))[mesh_face_valid].mean() * 1000)
/Anaconda3/envs/OSX1/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/OSX/main/../data/UBody/UBody.py:666: RuntimeWarning: Mean of empty slice.
  np.sqrt(np.sum((mesh_out_face_align - mesh_gt_face) ** 2, 1))[mesh_face_valid].mean() * 1000)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:17<00:00,  8.55s/it]
PA MPVPE (All): 60.88 mm
PA MPVPE (Hands): 11.00 mm
PA MPVPE (Face): nan mm

MPVPE (All): 153.83 mm
MPVPE (Hands): 71.00 mm
MPVPE (Face): nan mm

PA MPJPE (Body): 66.53 mm
PA MPJPE (Hands): 11.25 mm

**Comment by linjing7** [comment]
Hi, do you pull the latest code? We have fixed the bug of `nan` in the latest version code. BTW, you can not downsample the frame rate from 30 to 1, since it will change the output name of the images and could not correctly match the annotation.

**Comment by KW-NJU** [comment]
> Hi, do you pull the latest code? We have fixed the bug of `nan` in the latest version code. BTW, you can not downsample the frame rate from 30 to 1, since it will change the output name of the images and could not correctly match the annotation.

Thanks for your reply! However, we don't have enough storage space to accommodate all those 500G+ images transformed from the videos, so are there any solutions to reduce the image size or may I only use several parts of your images to get the same testing results as yours? Thanks a lot!

**Comment by linjing7** [comment]
@KW-NJU There are two possible solutions. The first one is that you can save the images in the `jpg` format instead of the 'png' format. The second one is that I could upload the test images tomorrow.

**Comment by KW-NJU** [comment]
> @KW-NJU There are two possible solutions. The first one is that you can save the images in the `jpg` format instead of the `png` format. The second one is that I could upload the test images tomorrow.

I've tried the first solution, and the size of the jpgs are really smaller than the pngs, so thanks a lot!

**Comment by KW-NJU** [comment]
> @KW-NJU There are two possible solutions. The first one is that you can save the images in the `jpg` format instead of the `png` format. The second one is that I could upload the test images tomorrow.

I'm afraid that there's another problem after I tried to test my jpgs: I found that the tester can't read those jpgs and got 0 images. Are there any solutions?

**Comment by linjing7** [comment]
@KW-NJU  Hi, you can add `if not os.path.exists(img_path): img_path = img_path.replace('.png', '.jpg')` in the dataloader.
