### ISSUE TITLE
problem when bash install.sh

### ISSUE THREAD

**Issue by matlab2017** [IDEA-Research/OSX#34]
Traceback (most recent call last):
  File "setup.py", line 169, in <module>
    long_description=readme(),
  File "setup.py", line 11, in readme
    with open('README.md', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

how to deal with, thanks.

**Comment by matlab2017** [comment]
should rename mmpose_READEME.md to READEME.md?

**Comment by linjing7** [comment]
Hi, I have modified the `setup.py`, please pull the latest code and try again.
