### ISSUE TITLE
'EGLPlatform' object has no attribute 'OSMesa'

### ISSUE THREAD

**Issue by HonglinChu** [IDEA-Research/OSX#36]
hello, thanks for your work, when i run demo.py, i got some errors as follow:
![image](https://github.com/IDEA-Research/OSX/assets/11087575/0282929d-dff4-4941-b986-d035ef52ceec)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/cb1f3262-6062-4f87-b56a-6bf6e0a34d25)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/dfc59d3c-d8d0-4ff4-bec8-d14d527f4310)

**Comment by HonglinChu** [comment]
But i can run success in hand4whole project by setting os.environ["PYOPENGL_PLATFORM"] = "osmesa" in vis.py

**Comment by linjing7** [comment]
Hi, please change `egl` to `osmesa` in this [line](https://github.com/IDEA-Research/OSX/blob/e4af4ced5ae13f459c9f07ec147a1924edf1e813/main/transformer_utils/mmpose/core/visualization/image.py#L20) and reinstall the environment.

**Comment by 3huo** [comment]
I got th same problem, did u solve it?
