### ISSUE TITLE
run demo.py get bad results

### ISSUE THREAD

**Issue by HonglinChu** [IDEA-Research/OSX#37]
Hello, when i run demo.py, i got bad result by visualizing the 3D joints and vertexes(it seems the params is wrong)，do you know what the problem might be？

![image](https://github.com/IDEA-Research/OSX/assets/11087575/23dc783c-5e6f-4b76-b830-2e83366dd5a8)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/69bbe8c1-404c-49f9-a14d-10ff900a44df)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/60c679b7-52a0-49c2-ba03-4748b2da72c4)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/a8053d81-9ed9-424e-be10-99a3180c9de8)

![image](https://github.com/IDEA-Research/OSX/assets/11087575/47c965cf-6e95-46c1-ab95-ab215c9b91f3)

**Comment by linjing7** [comment]
Hi, could you please show the `render.jpg` in the `output` folder?

**Comment by HonglinChu** [comment]
I can not  run render_mesh to get render.jpg,  so i have to  visualize the 3D joints, but the 3D  joints seems wrong.
![image](https://github.com/IDEA-Research/OSX/assets/11087575/943f72f6-0e66-402d-a4b9-0adfeea95d9c)

**Comment by linjing7** [comment]
Hi, if you want to use the OSMesa mode, please change `egl` to `osmesa` in this [line](https://github.com/IDEA-Research/OSX/blob/e4af4ced5ae13f459c9f07ec147a1924edf1e813/main/transformer_utils/mmpose/core/visualization/image.py#L20) and reinstall the environment.

**Comment by HonglinChu** [comment]
OSX/common/utils/display_utils.py

`from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

def display_body(
        model_info,
        model_faces=None,
        with_joints=False,
        kintree_table=None,
        ax=None,
        batch_idx=0,
        show=True,
        savepath=None,scale=1):
    """
    Displays mesh batch_idx in batch of model_info, model_info as returned by
    generate_random_model
    """
    if ax is None:
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
    verts, joints = model_info['verts'][batch_idx], model_info['joints'][
        batch_idx]
    if model_faces is None:
        ax.scatter(verts[:, 0], verts[:, 1], verts[:, 2], alpha=0.2)
    else:
        mesh = Poly3DCollection(verts[model_faces], alpha=0.2)
        face_color = (141 / 255, 184 / 255, 226 / 255)
        edge_color = (50 / 255, 50 / 255, 50 / 255)
        mesh.set_edgecolor(edge_color)
        mesh.set_facecolor(face_color)
        ax.add_collection3d(mesh)
    if with_joints:
        draw_skeleton(joints, kintree_table=kintree_table, ax=ax)
    else:
        ax.scatter(joints[:, 0], joints[:, 1], joints[:, 2], color='r')

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    
    ax.set_xlim(-scale, scale)
    ax.set_ylim(-scale, scale)
    ax.set_zlim(-scale, scale)
    #ax.view_init(azim=-90, elev=90)
    
    #cam_equal_aspect_3d(ax, verts.numpy(),flip_x=False)
    
    ax.view_init(azim=-90, elev=-90) # z轴旋转，y轴旋转

    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
    
    if savepath:
        print('Saving figure at {}.'.format(savepath))
        plt.savefig(savepath, bbox_inches='tight', pad_inches=0)
    if show:
        plt.show()
    return ax

def draw_skeleton(joints3D, kintree_table, ax=None, with_numbers=True):
    if ax is None:
        fig = plt.figure(frameon=False)
        ax = fig.add_subplot(111, projection='3d')
    else:
        ax = ax

    colors = []
    left_right_mid = ['r', 'g', 'b']
    kintree_colors = [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1]
    for c in kintree_colors:
        colors += left_right_mid[c]
    # For each 24 joint
    for i in range(1, kintree_table.shape[1]):
        j1 = kintree_table[0][i]
        j2 = kintree_table[1][i]
        ax.plot([joints3D[j1, 0], joints3D[j2, 0]],
                [joints3D[j1, 1], joints3D[j2, 1]],
                [joints3D[j1, 2], joints3D[j2, 2]],
                color=colors[i], linestyle='-', linewidth=2, marker='o', markersize=5)
        if with_numbers:
            ax.text(joints3D[j2, 0], joints3D[j2, 1], joints3D[j2, 2], j2)
    return ax`

**Comment by linjing7** [comment]
Hi, do you use the latest code? I clone the code from GitHub and test it just now, there isn't anything wrong with the result. When I run `python demo.py --gpu 0`, the render.jpg is as followed:
![render](https://github.com/IDEA-Research/OSX/assets/70081899/68cbcc20-3436-473a-955d-589dd9a00f8b)
And when I test OSX on your image, the result is:
![render](https://github.com/IDEA-Research/OSX/assets/70081899/ce7acf4f-88a6-40d8-b207-08455d479a20)

**Comment by HonglinChu** [comment]
Hi， i re-downloaded the code and reinstall the env，and still got bad results，could you share me smplx and smpl files by google cloud？

**Comment by HonglinChu** [comment]
Hi， when i comment yolov5 part， i can get better result.
![image](https://github.com/IDEA-Research/OSX/assets/11087575/4f3cce8a-e5c3-4e4d-b666-8199748efdd1)
Even though I'm not using yolov5, the results are still inconsistent, but better than before

**Comment by linjing7** [comment]
@HonglinChu Hi, it seems that the channel order of your image is BGR instead of RGB. Do you use the latest code?

**Comment by HonglinChu** [comment]
Thank you，the problem is solved when i reinstall the cudatoolkit=11.x

**Comment by linjing7** [comment]
Okay, happy to hear this news!
