### ISSUE TITLE
osx_vit_l.pth and osx_vit_b.pth

### ISSUE THREAD

**Issue by yxdydgithub** [IDEA-Research/OSX#38]
How did you to train the models about osx_vit_l.pth and osx_vit_b.pth?

**Comment by linjing7** [comment]
Hi, we use the pretrained models from [ViTPose](https://github.com/ViTAE-Transformer/ViTPose).

**Comment by jerriebright** [comment]
Hi, osx_vit pth file is just the backbone (from ViTPose paper) to train your encoder and isn't the ckpt that is finetuned on your encoder right?

**Comment by linjing7** [comment]
Yes, osx_vit pth file is the backbones pretrained in the COCO dataset using ViTPose repo.
