### ISSUE TITLE
Is it possible to make this model lighter for using mobile phone?

### ISSUE THREAD

**Issue by noeykan** [IDEA-Research/OSX#39]
Hi! Thank you for sharing your great work.

I have a question about porting to mobile phones.
I'm a newbie in this field, so please bear with me.

Do you think it is possible to make this model lighter for using mobile phones?

If you think it is possible, could you give me any tips for me? Thanks!

**Comment by linjing7** [comment]
Hi, thanks for your interest. You can try our model with the setting `--encoder_setting osx_b --decoder_setting wo_decoder`.  The speed is quite fast. If you want to apply it on mobile devices, I think you can try a tiny encoder such as the `vit_tiny`.

**Comment by noeykan** [comment]
Thank you for your kind reply!
I tried your settings, but encoder setting fails on demo.py

Decoder setting works:
`python demo.py --gpu 0 --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar`

Encoder setting doesn't work:
`python demo.py --gpu 0 --encoder_setting osx_b`
```
>>> Using GPU: 0
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/home/ubuntu/anaconda3/envs/osx_cuda11.7/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
05-23 01:28:40 Load checkpoint from ../pretrained_models/osx_l.pth.tar
05-23 01:28:40 Creating graph...
Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    demoer._make_model()
  File "/home/ubuntu/pose/OSX/main/../common/base.py", line 217, in _make_model
    model.load_state_dict(new_state_dict, strict=False)
  File "/home/ubuntu/anaconda3/envs/osx_cuda11.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.encoder.task_tokens: copying a param with shape torch.Size([1, 31, 1024]) from checkpoint, the shape in current model is torch.Size([1, 31, 768]).
	size mismatch for module.encoder.pos_embed: copying a param with shape torch.Size([1, 193, 1024]) from checkpoint, the shape in current model is torch.Size([1, 193, 768]).
...
```

I guess this happens when loading checkpoint osx_l.pth.tar, because encoder setting is osx_b.
However, I couldn't find any osx_b models in pretrained_models folder. 

If I try with pretrained_model `osx_vit_b.pth`, another error occurs.
`python demo.py --gpu 0 --encoder_setting osx_b --pretrained_model_path ../pretrained_models/osx_vit_b.pth`

```
>>> Using GPU: 0
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/home/ubuntu/anaconda3/envs/osx_cuda11.7/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
05-23 01:34:11 Load checkpoint from ../pretrained_models/osx_vit_b.pth
05-23 01:34:11 Creating graph...
Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    demoer._make_model()
  File "/home/ubuntu/pose/OSX/main/../common/base.py", line 213, in _make_model
    for k, v in ckpt['network'].items():
KeyError: 'network'
```

1. Could you let me know how can I try with encoder_setting osx_b?

2. Also, do you have any plans in the future to upload more light-weight pre-trained models like osx_s? This would be really helpful for me.

Thank you!

**Comment by linjing7** [comment]
Hi, you can use the code and train osx_b by yourself, the training command is:
`python train.py --gpu 0 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16 --encoder_setting osx_b --decoder_setting wo_decoder`

**Comment by noeykan** [comment]
@linjing7 Thank you for your answer!
I have one more question about using tiny encoder.

If I want to use a tiny encoder like TinyVit or EfficientVit(pretrained) in OSX, is it okay just to replace VitPose with those tiny modules directly? (Need to train once, OSX)

Or, should we first replace the transformer of VitPose, and then use this VitPose as an encoder of OSX? (Need to train twice, VitPose and OSX)

**Comment by linjing7** [comment]
Hi, it would be better to pretrain tiny ViT on the COCO 2d keypoints datasets, and then use it as the encoder of OSX.

**Comment by noeykan** [comment]
Thank you :)
