### ISSUE TITLE
When will the ubody dataset would be released?

### ISSUE THREAD

**Issue by FANzhaoxin666** [IDEA-Research/OSX#4]

**Comment by linjing7** [comment]
Hi, thanks for your interest in our work. We plan to release UBody by about 15, April.

**Comment by zxk19981227** [comment]
So, it's 19,April now, would it be released?

**Comment by linjing7** [comment]
@zxk19981227 Hi, thanks for your interest. In fact, I have prepared the data and upload it into the google drive. Now the data licence is being checked  by our the legal department of our academy. Once they think it's okay, I will release the link. I think it would be ready this week.
<img width="979" alt="image" src="https://user-images.githubusercontent.com/70081899/232986628-92385ffc-1704-44ce-8a7c-c2968100a02d.png">

**Comment by zxk19981227** [comment]
Could you send me the download linke in private? My email address is 2020000903@ruc.edu.cn. I promise not using it or public it
