### ISSUE TITLE
UBody data visualization

### ISSUE THREAD

**Issue by ZhengdiYu** [IDEA-Research/OSX#40]
Hi, I was managing to render your UBody dataset. But I found the format is a bit different from the network predictions. Is there a script to do this? I could already visualize the mesh by projection, but still having difficulties in doing a rendering.
![image](https://github.com/IDEA-Research/OSX/assets/63605407/04d695d3-4c59-4ef0-a461-c0eece987c58)
How can we render something like the teaser below?:
![image](https://github.com/IDEA-Research/OSX/assets/63605407/e78ca9f7-11b7-4f10-8efa-2b9448ef9905)

Thank you

**Comment by linjing7** [comment]
Hi, you can input the SMPLX parameters into the smplx layer and then render the mesh with `[render_mesh()](smplx_mesh_cam)`. You can refer to `demo.py`.

**Comment by ZhengdiYu** [comment]
> Hi, you can input the SMPLX parameters into the smplx layer and then render the mesh with [render_mesh()](https://github.com/IDEA-Research/OSX/blob/048c91b244bb4f763e5e750ae87b6ffe387df2a5/common/utils/vis.py#L127) function. You can refer to `demo.py`.

Thanks for your reply. What is the cam_param I need to use? Should I use the one from the annotation file, or should I compute a focal and princpt according to the bbox (just like demo.py)?

**Comment by linjing7** [comment]
Hi, you can try both solutions. I think the second choice is more reasonable.

**Comment by ZhengdiYu** [comment]
> Hi, you can try both solutions. I think the second choice is more reasonable, that is, computing a focal and princpt according to the bbox.

Thanks for your reply. May I ask which part of How2Sign dataset you have used in UBody dataset? And how did you obtain the `ann['valid_label']`? I found in Fitness folder, the `ann['valid_label']` is either 0 or 2, and it could be 0 even if the smplx_param exists. For example, the Fitness scene, there are many videos that has many `ann['valid_label'] == 0` for the first several tens of frames (e.g. Fitness_S1_Trim1 starts from 000051.png).

**Comment by linjing7** [comment]
Hi, I'm sorry that I do not clearly remember the exact subset of `How2Sign`. I think you can find the matching by comparing the video length with those in  `How2Sign`. For the second question, we obtain the `valid_label` by manual checking, that is, we ask human annotators to compare the rendering results with the original image. If the rendered mesh is highly aligned and consistent with the original image, we define it as valid by setting `valid_label=2`. If the image is invalid, we set `valid_label=0`. `valid_label=1` correspond to the samples that are between these two states.
