### ISSUE TITLE
demo/demo.py：Virtual environment requirements for demo.py operation

### ISSUE THREAD

**Issue by diplomatist** [IDEA-Research/OSX#42]
The use of demo. py did not inform the specific usage environment, including versions of mmcv, mmpose, and mmdet. I attempted to install `mmcv=1.6.2, mmpose=0.29.0, and mmdet=2.23.0`
But the following error will be reported:
![image](https://github.com/IDEA-Research/OSX/assets/74148589/2e8cc273-3bb4-45ec-9c8e-57ae3c59a658)
The file related to `demo.py` contains' `from config import cfg` ', which is an incorrect reference path
Fix bug:
Copying `main/config.py` to the project root directory can solve the bug.

**Comment by linjing7** [comment]
Hi, do you install your environment following the instruction by running `bash install.sh`? We have assigned the version of the packages in it.
