### ISSUE TITLE
about pre-trained models

### ISSUE THREAD

**Issue by matlab2017** [IDEA-Research/OSX#43]
Hello. How do you get pretrained encoder osx_vit_l.pth and osx_vit_b.pth? Is it trained on MSCOCO, Human3.6m, MPII from scratch?

**Comment by matlab2017** [comment]
The model is downloaded directly in this project (https://github.com/ViTAE-Transformer/ViTPose)? Did you do any extra training?
thanks very much

**Comment by linjing7** [comment]
Hi, I have tried to finetune the models on the COCO-WholeBody datasets, but it does not work. Thus, I use the original pretrained model from ViTPose.

**Comment by matlab2017** [comment]
How many A100s did you used?  How long will it take?  I want to try training OSX_b, but one 4090 can be used.

**Comment by linjing7** [comment]
Hi, you train OSX_l on 1 A100-80G for 2 days. If you do not have enough GPU, you can run a lighter model by adding `--decoder_setting wo_decoder` or `--decoder_setting wo_face_decoder`.
