### ISSUE TITLE
运行demo.py出现的问题

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#47]
<img width="415" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/fe5d1164-2c54-4411-ae22-c149bbaa7852">

在进行python demo.py --gpu 0 --img_path IMG_PATH --output_folder OUTPUT_FOLDER运行时出现Unable to load EGL library，不知道问题出在哪块

**Comment by linjing7** [comment]
Hi, I have never run OSX on Windows system. Do you install `oemesa` and `pyopengl`? Beides, you can try mask out this line: [os.environ["PYOPENGL_PLATFORM"] = "egl"](https://github.com/IDEA-Research/OSX/blob/07f1b0212cf1e84a361957b12a3ffe56f7476210/common/utils/vis.py#L8) or change it into `os.environ["PYOPENGL_PLATFORM"] = "egl"`.

**Comment by minsiyuan** [comment]
感谢您的解答，问题已解决
但是又遇到关于GPU内存不足的问题，用网上终端清除缓存的办法没能解决，这种情况下是否需要服务器跑代码？还是换显卡呢？



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "IDEA-Research/OSX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月18日(星期天) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-Research/OSX] 运行demo.py出现的问题 (Issue #47)





 
Hi, I have never run OSX on Windows system. Do you install oemesa and pyopengl? Beides, you can try mask out this line: os.environ["PYOPENGL_PLATFORM"] = "egl" or change it into os.environ["PYOPENGL_PLATFORM"] = "egl".

**Comment by linjing7** [comment]
We have successfully tested in 24G RTX3090.
