### ISSUE TITLE
提示GPU内存不足

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#48]
<img width="416" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/0e8c28e9-c689-4efe-a6fc-b2c20143911c">
在跑demo.py时，提示GPU内存不足，用网上终端清除缓存的方法也不行，如果不换显卡有别的办法吗？

**Comment by linjing7** [comment]
Hi, which GPU do you use? We have tested in 24G RTX3090. If you don't have enough memory, you can use the light-weight model by adding `--decoder_setting wo_decoder.`

**Comment by minsiyuan** [comment]
GPU是NVIDIA GeForce MX150，2G的，添加--decoder_setting wo_decoder依旧出现同样的问题，是否需要替换显卡，如果在unubtu22.04上进行可以吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-Research/OSX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月22日(星期四) 中午12:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-Research/OSX] 提示GPU内存不足 (Issue #48)





 
Hi, which GPU do you use? We have tested in 24G RTX3090. If you don't have enough memory, you can use the light-weight model by adding --decoder_setting wo_decoder.

**Comment by minsiyuan** [comment]
GPU是NVIDIA GeForce MX150，2G的，添加--decoder_setting wo_decoder依旧出现同样的问题，所以需要容量是多少呢？

**Comment by linjing7** [comment]
2G显存是不够的，需要的显存最少是12G
