### ISSUE TITLE
Is there any pretrained model for upper body keypoint detection with high accuracy?

### ISSUE THREAD

**Issue by p0mad** [IDEA-Research/OSX#49]
Hi, Any pretrained model that can be used for high accuracy upper body key point detection? (pose estimation of upper body that can supports face + hands + pose)

Thanks
Best regards

**Comment by linjing7** [comment]
Hi, thanks for your interest. Currently, we do not plan to opensource our motion annotation pipeline. We may consider releasing it in the future.
