### ISSUE TITLE
关于\OSX-main\\OSX-main\main\\..\\dataset\\Human36M\\J_regressor_h36m_smplx.npy文件

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#51]
![image](https://github.com/IDEA-Research/OSX/assets/56496112/6c879e22-a9ed-4f8f-bdee-aeb29c912bef)
训练模型显示J_regressor_h36m_smplx.npy没有，但是在data为根目录里有，是否需要修改文件的路径？

**Comment by linjing7** [comment]
你好，你的进度条显示你的测试集是空的，你有按照要求正确下载AGORO数据集，并放置在正确的位置吗？

**Comment by linjing7** [comment]
这个是coco_wholebody_train_v1.0.json出错了，我建议你重新下载一下

**Comment by minsiyuan** [comment]
![sunlogin_20230705225612](https://github.com/IDEA-Research/OSX/assets/56496112/10978841-a04c-4ffb-954a-ee8bb0cfb678)
这次是coco_wholebody_val_v1.0.json的问题吗？我重新下载之后也不行，不确定问题出现在哪？

**Comment by linjing7** [comment]
这次是MSCOCO_train_SMPLX.json的问题

**Comment by minsiyuan** [comment]
![sunlogin_20230706133919](https://github.com/IDEA-Research/OSX/assets/56496112/48486bbe-b58a-4374-b0fb-117230d8fd63)
谢谢解答，问题已解决，但出现numpy数组容量的问题，需要扩大内存吗？试过在pycharm中修改运行内存不行
