### ISSUE TITLE
numpy问题

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#55]
![sunlogin_20230706133919](https://github.com/IDEA-Research/OSX/assets/56496112/3853136c-60ae-4ec9-9fb6-fe14b0cb1bc5)
显示numpy数组容量不足问题，通过扩大pycharm运行内存还是一样的问题，需要修改float的精度吗？有没有其他好的解决办法？

**Comment by minsiyuan** [comment]
需要扩大内存吗？训练需要的内存容量是多少？

**Comment by linjing7** [comment]
你好，内存我没仔细计算过，inference的话，应该至少需要16G memory

**Comment by minsiyuan** [comment]
<img width="415" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/e0f7c71c-8542-4854-be91-040cfb655caa">
在运行python tensor_to_numpy_parameter.py --dataset_path $PATH1与python agora2coco.py --dataset_path $PATH1 --human_model_path $PATH2出现args未定义，以及namespace的问题，找不出问题所在？

**Comment by minsiyuan** [comment]
已按照要求下载解压文件
