### ISSUE TITLE
agora问题

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#57]
<img width="415" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/04dab714-103f-424d-b2f7-630e3d779f7c">
在AGORA dataset parsing process部分，运行python tensor_to_numpy_parameter.py --dataset_path $PATH1、python agora2coco.py --dataset_path $PATH1 --human_model_path $PATH2和python affine_transom.py --dataset_path $PATH1 --out_height 512 --out_width 384出现错误，不确定问题出现在哪？

**Comment by linjing7** [comment]
你好，我已经修正了bugs，你可以重新下载最新的代码，试一下

**Comment by minsiyuan** [comment]
<img width="415" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/2e2bb4bd-6339-4286-b9af-9333d4a1b574">
在第二步时python agora2coco.py --dataset_path $PATH1 --human_model_path $PATH2，出现AttributeError: 'Namespace' object has no attribute 'root_path' 不确定是我引入的包有误还是有重复的变量名称？

**Comment by linjing7** [comment]
你好，你可以把[这一行](https://github.com/IDEA-Research/OSX/blob/edcdcacc2a81318416e71f101fb3b63a955109b2/tool/AGORA/agora2coco.py#L62)改为`root_path = args.dataset_path`
