### ISSUE TITLE
run out of input

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#58]
![sunlogin_20230723155800](https://github.com/IDEA-Research/OSX/assets/56496112/263358e7-ef1a-46bb-bd2a-44ffa07cf656)
运行python train.py --gpu 0,1,2,3 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16提示读入文件问题，是哪个文件下载有误吗？

**Comment by linjing7** [comment]
这个可能是你的进程数超过你电脑cpu承载能力了，你可以把[num_threads](https://github.com/IDEA-Research/OSX/blob/d0c8ef5ce65cfc31f69982134b120de7697f1ef3/main/config.py#L44)改小试试。

**Comment by minsiyuan** [comment]
收到，感谢解答，但Human36M中images文件中的images.tar gzab—images.tar.gzag无法解压，下载的网址上写的是二进制文件，和images.tar.gzaa的文件形式不一样，在win环境下有没有解决的办法？
<img width="89" alt="image" src="https://github.com/IDEA-Research/OSX/assets/56496112/d3339eb2-55bd-415e-9984-af3d2630653d">
AGORA文件的下载的训练集和其他文件和要求中的一样，但python test.py --gpu 0,1,2,3 --exp_name output/train_setting2/ --pretrained_model_path ../output/train_setting2/model_dump/snapshot_139.pth.tar --testset AGORA --agora_benchmark --test_batch_size 64 --decoder_setting wo_decoder测试时，result文件中依旧没有结果，不知道问题出现在哪？是否需要上一步训练测试结束后在进行吗？

**Comment by linjing7** [comment]
你好，AGORA你训练多久呢？我没有在windows环境训练过，我建议你在ubuntu环境中进行实验吧。
