### ISSUE TITLE
How to transition from smplx to smpl

### ISSUE THREAD

**Issue by LiuShiyu95** [IDEA-Research/OSX#60]
Thank you for your great work!
I'm new to smpl models so the question might be stupid. I run demo.py and got the following result:
        smplx_joint_proj ========== torch.Size([1, 137, 2])
        smplx_mesh_cam ========== torch.Size([1, 10475, 3])
        smplx_root_pose ========== torch.Size([1, 3])
        smplx_body_pose ========== torch.Size([1, 63])
        smplx_lhand_pose ========== torch.Size([1, 45])
        smplx_rhand_pose ========== torch.Size([1, 45])
        smplx_jaw_pose ========== torch.Size([1, 3])
        smplx_shape ========== torch.Size([1, 10])
        smplx_expr ========== torch.Size([1, 10])
        cam_trans ========== torch.Size([1, 3])
How do I convert this result into smpl model parameters, or can I use the smpl model to execute the OSX model?

**Comment by linjing7** [comment]
Hi, to convert SMPL into SMPLX, you need to fit the mesh of them to be similar. You can refer to [this repo](https://github.com/vchoutas/smplx/tree/main/transfer_model).

**Comment by LiuShiyu95** [comment]
> Hi, to convert SMPL into SMPLX, you need to fit the mesh of them to be similar. You can refer to [this repo](https://github.com/vchoutas/smplx/tree/main/transfer_model).

Thank you for your reply. I also want to ask you how to accurately render from mesh to 2d image, do you have some references? Thanks a lot!

**Comment by linjing7** [comment]
Hi, you can refer the visualization in our [demo](https://github.com/IDEA-Research/OSX/blob/13df1cbf9cc5ae72deb46ce7ab5832e7bcb8bd9d/demo/demo.py#L96).

**Comment by LiuShiyu95** [comment]
> Hi, to convert SMPL into SMPLX, you need to fit the mesh of them to be similar. You can refer to [this repo](https://github.com/vchoutas/smplx/tree/main/transfer_model).

I'm sorry to bother you again, I tried converting SMPLX to SMPLH model as you suggested, but there is an error that I have not been able to resolve. Do you have any good suggestions please? The error is represented as follows:

`AttributeError: 'Struct' object has no attribute 'hands_componentsl'`

I printed the parameters of the imported smplh model and got the following results, which do not match the parameters needed in the code in a significant way.

```
J_regressor_prior ============= (24, 6890)
f ============= (13776, 3)
J_regressor ============= (52, 6890)
kintree_table ============= (2, 52)
J ============= (24, 3)
weights_prior ============= (6890, 24)
weights ============= (6890, 52)
posedirs ============= (6890, 3, 459)
bs_style ============= ()
v_template ============= (6890, 3)
shapedirs ============= (6890, 3, 16)
bs_type ============= ()
```

And I tried to import some of the parameters from SMPLX directly into SMPLH, but the following situation occurs, and I would like to ask why the mesh moves down a part of the whole?


![smplx](https://github.com/IDEA-Research/OSX/assets/72343712/29b4ff69-eed0-4fc4-82e5-ede9f29a1893)
![smplh](https://github.com/IDEA-Research/OSX/assets/72343712/1d70d126-3ab7-45ab-b695-507bd7b53cdb)

Sorry again for the trouble and thank you very much for helping me a lot!

**Comment by linjing7** [comment]
Hi, the hand pose parameters of SMPLH and SMPLX of one person are the same. Thus, you can not directly use one to replace another. You need to optimize the parameter following the repo.

**Comment by LiuShiyu95** [comment]
I'll try again. Thanks.
