### ISSUE TITLE
Training details on 3DPW

### ISSUE THREAD

**Issue by Michel-liu** [IDEA-Research/OSX#63]
Hi~ I'm wondering about the training details on the 3DPW dataset, such as training epochs and dataset config. 

Currently, I set the training epoch as `14` and the dataset config as follows.
<img width="488" alt="image" src="https://github.com/IDEA-Research/OSX/assets/27548562/955add0b-23f8-420a-98f5-86e61ed595dc">
BTW, is there anything else that I need to modify?

**Comment by linjing7** [comment]
Hi, thanks for your interest. We train on 3DPW using the [hmr-benchmark](https://github.com/smplbody/hmr-benchmarks) repo with [mix8](https://github.com/smplbody/hmr-benchmarks/blob/dev/configs/mixed/resnet50_hmr_mix8.py) config. The model setting is `--encoder_setting osx_l --decoder_setting wo_decoder`.

**Comment by Michel-liu** [comment]
Thanks for your quick reply! I get it.
