### ISSUE TITLE
train

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#66]
![image](https://github.com/IDEA-Research/OSX/assets/56496112/93e3546c-137f-45e2-9f24-27b0a2e629b8)
在Setting1:  Train on MSCOCO, Human3.6m, MPII and Test on EHF and AGORA-val时训练python train.py --gpu 0,1,2,3 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16，出现内存不足的问题，请问如何添加轻量级进行训练代码？
![image](https://github.com/IDEA-Research/OSX/assets/56496112/bfe38f9e-3f23-46d2-904d-c7980a7533fc)
并且测试时test on EHF
python test.py --gpu 0,1,2,3 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset EHF
test on AGORA-val
python test.py --gpu 0,1,2,3 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset AGORA
出现如上问题，不知道问题出在哪，是否还是内存不足的问题？如何解决？
在rtx 3090 24G，ubuntu系统进行的

**Comment by linjing7** [comment]
你好，
1. 显寸不足的问题：你可以把train_batch_size减小，或者使用轻便一些的encoder和decoder，加入`--encoder_setting osx_b --decoder_setting wo_decoder`，你也可以nvidia-smi看一下哪些卡空着，然后指定使用这张卡，例如3号卡空着，就写--gpu 3
2. 第二个问题是train和test的model setting不一致导致的，你要保证train和test时的`--encoder_setting` 和 `--decoder_setting` 是相同的

**Comment by minsiyuan** [comment]
好的，感谢解答
请问MPII中data大文件中的images里的图片数据从哪里下载？
