### ISSUE TITLE
How to rotate mesh and key points simultaneously

### ISSUE THREAD

**Issue by LiuShiyu95** [IDEA-Research/OSX#67]
Hi, Thank you for your great job!

I used the SMPL model and your camera and keypoint conversion method, and at the initial value, the human body was inverted and on the back. May I ask if I can modify the global rotation parameters in the SMPL model or how to change the projection so that the final generated mesh and key points can be aligned. I'm trying to use
` global_orientation [:, 0]=global_orientation [:, 0]+np. pi`
, but the first frame obtained is correct, and the subsequent frames are all messy

**Comment by linjing7** [comment]
Thanks for your interest. You can transform the global orient axis angle to matrix, and then multiply it by a rotation matrix. And then, transform the multiplied orient matrix into orient axis angle.

**Comment by LiuShiyu95** [comment]
Thank you for your reply. 

I am currently experiencing a visualization issue. After using the SMPL parameters I set myself to generate the mesh, I processed it according to your method and found that some images may have the following problem. I tried to modify the camera's position, but the problem still exists. Do you have any good solutions?

![图片](https://github.com/IDEA-Research/OSX/assets/72343712/bcc1f482-fd22-41a5-a3e2-bbd76de0fe26)
![图片](https://github.com/IDEA-Research/OSX/assets/72343712/87b61725-54e9-4b97-9a86-87ba982cc7c2)

**Comment by linjing7** [comment]
The SMPL parameters you manually set could be easy to be physically implausible. If you want to set the SMPL param by yourself, I think it would be better to sample a pose from [VPoser](https://github.com/nghorbani/human_body_prior).

**Comment by LiuShiyu95** [comment]
I used the SMPL parameter output from the motion diffusion model for visualization, and I also imported the corresponding OBJ file into the meshlab. I found that mesh is reasonable in 3D, but there were some exceptions in the results when casting to 2D
