### ISSUE TITLE
images文件

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#68]
好的，感谢解答
请问MPII中data大文件中的images里的图片数据从哪里下载？

**Comment by minsiyuan** [comment]
在AGORA进行测试时python test.py --gpu 0,1,2,3 --exp_name output/train_setting2/ --pretrained_model_path ../output/train_setting2/model_dump/snapshot_139.pth.tar --testset AGORA --agora_benchmark --test_batch_size 64 --decoder_setting wo_decoder，result文件中没有任何内容，AGORA文件也按照要求将数据进行下载，不确定问题出现在哪？

**Comment by linjing7** [comment]
1. MPII的images在[MPII官网](http://human-pose.mpi-inf.mpg.de/#download)下载就行
2. 有报错信息吗？AGORA下载后需要按照`tool`文件夹里边进行处理，你有吗？

**Comment by minsiyuan** [comment]
没有报错，问题已解决，谢谢解答
