### ISSUE TITLE
SVD

### ISSUE THREAD

**Issue by minsiyuan** [IDEA-Research/OSX#69]
![image](https://github.com/IDEA-Research/OSX/assets/56496112/097f22da-b152-4b1f-a6a9-eaf36b91cca3)
![image](https://github.com/IDEA-Research/OSX/assets/56496112/d28616c3-ebf6-4fc6-bfcd-3cf651998bf2)
运行第一步python test.py --gpu 0,1,2,3 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset EHF，出现SVD did not converge
第二步python test.py --gpu 0,1,2,3 --exp_name output/train_setting1/ --pretrained_model_path ../output/train_setting1/model_dump/snapshot_13.pth.tar --testset AGORA，显示KeyError:'pa_mpvpe_all'
请问这两个问题出现的原因在哪？

**Comment by linjing7** [comment]
1. 这个是因为你训练出来的模型有问题。你可以用你训练出来的预训练模型，跑一下demo，看一下可视化结果。
2. 这个是因为你的AGORA testset是空的，导致计算指标的时候，没有pa_mpvpe_all这个key
