### ISSUE TITLE
Questions about datasets optimization

### ISSUE THREAD

**Issue by cyk990422** [IDEA-Research/OSX#70]
I noticed that when you optimized the dataset, you changed the pseudo 3d labels of the initial OSX capture (whether containing pose, shape, and
smpl3d point? ) together with vision transformer-based 2d detection to build a new dataset, fine-tuned on initial OSX. This is a simple and effective method. I would like to ask whether it is necessary to change the weight of loss during the fine-tuning process, such as increasing the weight of 2d supervision?

**Comment by linjing7** [comment]
Yes, during fine-tuning process, the weight of 2d supervision is larger.
