### ISSUE TITLE
The question about the AGORA dataset

### ISSUE THREAD

**Issue by sherlhw** [IDEA-Research/OSX#74]
How are the 'gt_verts', 'gt_joints_3d', 'gt_joints_2d' folders generated in the AGORA dataset?

**Comment by linjing7** [comment]
Hi, please refer to this [instrunction](https://github.com/IDEA-Research/OSX/blob/main/tool/AGORA/README.md).

**Comment by sherlhw** [comment]
Thank you very much for your reply. I have another question. What data are the different model files trained by? Is osx_l_path.tar the model after Ubody fine-tuning?

**Comment by linjing7** [comment]
Hi, `osx_l_agora.pth.tar `is pretrained on MSCOCO, MPII, H3.6M and AGORA datasets, `osx_l_wo_decoder.pth.tar` and `osx_l.pth.tar`are pretrained on MSCOCO, MPII, H3.6M. `osx_vit_b.pth` and `osx_vit_l.pth` are pretrained with the MSCOCO datasets for 2D keypoints detection.

**Comment by sherlhw** [comment]
Thank you very much for your reply.
