### ISSUE TITLE
Question about model effects

### ISSUE THREAD

**Issue by sherlhw** [IDEA-Research/OSX#77]
May I ask why the test results of the model I trained according to the code you gave me on EHF are quite different from the model test results you provided? Figure 1 is the result of your model and Figure 2 is the result of my trained model.
![1](https://github.com/IDEA-Research/OSX/assets/97173205/12b225fc-9a8e-45f8-a266-5576bc4703b7)
![2](https://github.com/IDEA-Research/OSX/assets/97173205/1186ff45-b678-45bb-b8e9-7e7664d5b300)

**Comment by linjing7** [comment]
Hi, the body results of yours is worse to ours while the face result is a little better. Do you use the pretrained `osx_vit_l.pth` model to initialize the encoder weight?

**Comment by sherlhw** [comment]
The training code I use is “python train.py --gpu 0,1,2,3 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16”,how should I add the pre-trained model 'osx_vit_l.pth'?

**Comment by linjing7** [comment]
Hi, have you downloaded `osx_vit_l.pth` in advance and put it in `pretrained_model` folder? Besides, in my experiments, I use batch_size=32 with 1 GPU, thus, my iteration number would be two times yours. To keep the same iteration number, you can try to use two GPU by changing  `--gpu 0,1,2,3` to `--gpu 0,1`.

**Comment by sherlhw** [comment]
I found a sentence in my log 'pretrained_model_path to... /pretrained_models/osx_l.pth.tar 'However, it is not in your log, what is the impact of this?

**Comment by sherlhw** [comment]
I have downloaded osx_vit_l.pth in advance and put it in pretrained_model folder.

**Comment by linjing7** [comment]
Hi, what's your testing command? Do you keep the same model setting during training and inference? Do you find `Load checkpoint from ... /pretrained_models/osx_l.pth.tar`  in your training log?

**Comment by sherlhw** [comment]
My test code is' python test.py --gpu 0,1 --exp_name... /output/train_setting2 --pretrained_model_path .. /output/train_setting2/model_dump/snapshot_13.pth.tar --testset EHF ', if there is 'Load checkpoint from ... /pretrained_models/osx_l.pth.tar' in the training log, start training from initialization or fine tuning, When I add the --continue parameter to the train code, it has this,  and when I don't add it, it doesn't.

**Comment by linjing7** [comment]
During training, your exp_name is `... /output/train_setting1`, why do you set it to `... /output/train_setting2` during testing? Besides, please make sure that the model settings keep the same during training and testing by adding `--encoder_setting osx_l --decoder_setting normal`.

**Comment by sherlhw** [comment]
The exp_name is my input error, excese me, if there is 'Load checkpoint from ... /pretrained_models/osx_l.pth.tar' in the training log, start training from initialization or fine tuning, When I add the --continue parameter to the train code, it has this, and when I don't add it, it doesn't.

**Comment by linjing7** [comment]
I think this would not matter because I have added this line in [OSX.py](https://github.com/IDEA-Research/OSX/blob/13df1cbf9cc5ae72deb46ce7ab5832e7bcb8bd9d/main/OSX.py#L441C10-L441C10). Please do the following things:
1. please make sure that the model settings keep the same during training and testing by adding `--encoder_setting osx_l --decoder_setting normal`
2. use 2 gpus and train again.

**Comment by sherlhw** [comment]
My model settings are the same as yours, I will train again, thanks for your reply.

**Comment by CC4747** [comment]
> The training code I use is “python train.py --gpu 0,1,2,3 --lr 1e-4 --exp_name output/train_setting1 --end_epoch 14 --train_batch_size 16”,how should I add the pre-trained model 'osx_vit_l.pth'?

Hi, which epoch did you get the result MPVPE 80 please? Thank you:)
