### ISSUE TITLE
Question about annotation files

### ISSUE THREAD

**Issue by tinatiansjz** [IDEA-Research/OSX#78]
Thanks for sharing us this excellent work and the code!

I am a little confused about the data preparation. Both the [data] and [SMPL-X parameters from NeuralAnnot] links of H36M, MPII, MPI-INF-3DHP datasets contain annotation files. What is the difference between those annotations?

**Comment by linjing7** [comment]
Hi, the annotation files in [data] provide bounding box and keypoints annotations. While [SMPL-X parameters from NeuralAnnot] provide SMPLX annotations.

**Comment by tinatiansjz** [comment]
Thanks for your reply. The question is solved.
