### ISSUE TITLE
Test on 3DPW

### ISSUE THREAD

**Issue by sherlhw** [IDEA-Research/OSX#79]
How to test on 3DPW? I use 'python test.py --gpu 0,1,2,3,4,5,6,7 --exp_name output/test_setting_8_3DPW --pretrained_model_path $GEMINI_DATA_IN1/code/OSX/output/train_setting_8/model_dump/snapshot_13.pth.tar --testset PW3D', but there is a bug:
![image](https://github.com/IDEA-Research/OSX/assets/97173205/bc0cc009-6e03-49e5-99e7-b792072f23e0)

**Comment by linjing7** [comment]
Hi, 3DPW only provides SMPL ground truth, without SMPL-X ground truth. For SMPL-version body-only experiments, we train and test with this [repo](https://github.com/smplbody/hmr-benchmarks) in the setting of [mix8](https://github.com/smplbody/hmr-benchmarks/blob/dev/configs/mixed/resnet50_hmr_mix8.py).

**Comment by sherlhw** [comment]
Sorry, but I still do not understand. Is it necessary to configure the hmr-benchmarks, and what exactly is the code used to train and test it?

**Comment by linjing7** [comment]
Yes, to perform the SMPL-version experiment, you need to use the hmr-benchmarks. You just need to use the encoder-only osx as the model and use the mix8 training config, then you can train and test it. Here I upload the [training code](https://drive.google.com/drive/folders/1ApNARUAiF9xaWQ3dEHDkW1SSBJ29HnKN?usp=drive_link) in the google drive and I hope it can help you.

**Comment by sherlhw** [comment]
Thank you very much for your reply. I'll try.

**Comment by linjing7** [comment]
Hi, this is the [training log](https://drive.google.com/file/d/1tPsiBHPM8530M327wnmf2h5GT9JReINL/view?usp=drive_link) and you can compare it with your training result.

**Comment by sherlhw** [comment]
Thanks, the training log has access permission, I have applied for it, please pass it.

**Comment by sherlhw** [comment]
OK, that's OK!
