### ISSUE TITLE
 whole-body annotation pipeline

### ISSUE THREAD

**Issue by PGogo** [IDEA-Research/OSX#8]
Hi, thanks for your great work!
Is this annotaion pipeline available now? How can i start with it?

**Comment by linjing7** [comment]
Hi, thanks for your interest! We are keeping improving the annotation pipeline to make it more robust and accurate. We would consider releasing the annotation code in the future.

**Comment by PGogo** [comment]
I feel that you are really invested in this work for every prompt reply. I am looking forward to it!
