### ISSUE TITLE
跑出来的视频人物抖动很明显，有什么解决方案吗？

### ISSUE THREAD

**Issue by baitian752** [IDEA-Research/OSX#81]

**Comment by linjing7** [comment]
你好，可以尝试[SmoothNet](https://github.com/cure-lab/SmoothNet)，对body pose做一个smooth，可以参考这个[demo](https://github.com/haofanwang/CLIFF/blob/main/demo.py)

**Comment by baitian752** [comment]
好的，感谢指导 ~
