### ISSUE TITLE
vit error

### ISSUE THREAD

**Issue by herochen7372** [IDEA-Research/OSX#82]
Hi, Can you help me for this error:

Exception has occurred: KeyError
"TopDown: 'ViT is not in the models registry'"

**Comment by HonglinChu** [comment]
I meet the same error

**Comment by HonglinChu** [comment]
mmpose==0.28.0  mmcv==1.7.1 or mmcv==1.6.0

**Comment by linjing7** [comment]
Hi, please refer to this [issue](https://github.com/IDEA-Research/OSX/issues/1).
