### ISSUE TITLE
关于FBX和T-Pose 

### ISSUE THREAD

**Issue by sarsigmadelta** [IDEA-Research/OSX#84]
您好，跑出来的动作导入FBX模型后，身体的动作是对的，但是手部的动作不对，原因是手部的T-Pose。根据MANO 数据定义的手部T-Pose，手部是微握拳的动作，　但是主流的FBX (maximo 等)的手部T-Pose 是手掌摊开的，所以会出现这个问题，请问有好的建议可以解决这个问题吗，谢谢

**Comment by henrycjh** [comment]
应该是smplx中flat_hand_mean设置的问题，加上或减去这个mean值就可以了，参考https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L630
https://github.com/vchoutas/smplx/blob/1265df7ba545e8b00f72e7c557c766e15c71632f/smplx/body_models.py#L737C15-L737C15
