### ISSUE TITLE
Train OSX from scratch (VITPose also) on depth images

### ISSUE THREAD

**Issue by GhostLate** [IDEA-Research/OSX#85]
I tried to train the OSX Base model on depth images to predict the SMPLX avatar. But the error is too big.

I used higher learning rate (1-e4) and epoch_num with image normalization (mean/std).
My original float32 depth images have a range in meters: [1.5: 3.5]. Total Dataset contains ~110k samples.

What do you think, is it possible to train OSX using depth images instead of RGB?
Any ideas would be welcome

**Comment by linjing7** [comment]
Hi, thanks for your interest! I think it is possible to train OSX using depth images. I think you should also input the normalized depth map. For example, plus to the root depth. It would be beneficial for the local pose learning. You can try OSX with the setting `--decode_setting wo_decoder`, which is faster and easier to converge.

**Comment by GhostLate** [comment]
Thank you, I'd tried and got some good results..
