### ISSUE TITLE
3D 骨骼点

### ISSUE THREAD

**Issue by Ninglily** [IDEA-Research/OSX#86]
您好，您的代码中是否用到了3D骨骼点？能否输出相关的数据或图像呢？麻烦您的指点，谢谢。

**Comment by linjing7** [comment]
你好，有输出3D骨骼点，你只需要把joint_cam保存下来就可以
https://github.com/IDEA-Research/OSX/blob/118cf97fb1f144930bf93d88794b525d579b2d0c/main/OSX_WoDecoder.py#L191
想要可视化的话，可以参考这个函数：
https://github.com/IDEA-Research/OSX/blob/118cf97fb1f144930bf93d88794b525d579b2d0c/common/utils/vis.py#L78

**Comment by linjing7** [comment]
@kekekou  Hi, `joint_cam` is 3D joints position. You can input a photo and get the 3D skeleton points by storing `joint_cam`.  We modified the joints number into 137 to ensure that the joints can match the 2D keypoints and we can use the 2D keypoints for supervision.

**Comment by kekekou** [comment]
> @kekekou Hi, `joint_cam` is 3D joints position. You can input a photo and get the 3D skeleton points by storing `joint_cam`. We modified the joints number into 137 to ensure that the joints index can match the 2D keypoints and we can use the 2D keypoints for supervision.

Sorry for the long delay in responding. I have found the 3D keypoints. Can I understand it as follows? First, train a keypoint estimation network based on ViT to estimate high-precision full-body keypoints. Then, convert the human mesh output from OSX into 3D keypoints and project them onto the image plane. Calculate the loss between the projected 3D keypoints and the estimated 2D keypoints until the mesh and 2D keypoints closely align with each other.

**Comment by linjing7** [comment]
No, you don't need to perform the fitting operation. You just need to save the 3D joints estimated by OSX.
