### ISSUE TITLE
Unable to load OpenGL library', 'libgcrypt.so.11

### ISSUE THREAD

**Issue by APeiZou** [IDEA-Research/OSX#88]
@ailingzengzzz @linjing7   运行demo.py的时候出现找不到库的错误， Unable to load OpenGL library', 'libgcrypt.so.11

**Comment by linjing7** [comment]
Hi, which platform do you use? Do you install the required packages (e.g., pyrender) following the instructions in README?

**Comment by APeiZou** [comment]
@linjing7 ubuntu，I have  install the required packages (e.g., pyrender) following the instructions in README

**Comment by linjing7** [comment]
It is something wrong with the visualization during rendering. I have not met this problem in my environment. You can refer to this [issue](https://stackoverflow.com/questions/65751536/importerror-libopengl-so-0-cannot-open-shared-object-file-no-such-file-or-dir).

**Comment by APeiZou** [comment]
@linjing7 您好，冒昧的问一下，你们最近有没有组织什么人体重建分享活动什么的呢？
