### ISSUE TITLE
How can I prepare folder "human_model_files"

### ISSUE THREAD

**Issue by eeyrw** [IDEA-Research/OSX#9]
I am a newbie of pose estimation and want to leverage the OSX to extract 3d mesh body model and try to inference with the code.  I have signed up a lot of account of xxx.is.tue.mpg.de and download a lot of models but turn out still not enough to preparing the folder according readme.  Here are downloaded files:
![image](https://user-images.githubusercontent.com/2088817/230757116-2ffe00da-7e86-4632-a531-626db5f16e7a.png)
Current match:
![image](https://user-images.githubusercontent.com/2088817/230757439-6d53ea6f-5b55-4f3b-bd57-703f66aea23f.png)
Any tips of that?

**Comment by linjing7** [comment]
Hi, you can download the model files by:
1. smpl: [SMPL_NEUTRAL.pkl](https://github.com/sampepose/smpl_models/raw/master/SMPL_NEUTRAL.pkl)
2. smplx: [MANO_SMPLX_vertex_ids.pkl and SMPL-X__FLAME_vertex_ids.npy](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=smplx_mano_flame_correspondences.zip), [SMPLX_NEUTRAL.pkl](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=SMPLX_NEUTRAL_2020.npz), [SMPLX_to_J14.pkl](https://github.com/vchoutas/expose#preparing-the-data). 
3. mano: [here](https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip)
4. flame:  [flame_dynamic_embedding.npy and flame_static_embedding.pkl](https://github.com/soubhiksanyal/RingNet/tree/master/flame_model), [FLAME_NEUTRAL.pkl](https://download.is.tue.mpg.de/download.php?domain=flame&resume=1&sfile=FLAME2019.zip). You need to rename `generic_model.pkl` to `FLAME_NEUTRAL.pkl`.

**Comment by eeyrw** [comment]
Thank for your tips and I finally collected complete files.
But the demo.py still need more..?
```
  File "E:\OSX\main\demo.py", line 37, in <module>
    from OSX import get_model
  File "E:\OSX\main\..\main\OSX.py", line 4, in <module>
    from nets.module import PositionNet, HandRotationNet, FaceRegressor, BoxNet, BoxSizeNet, HandRoI, FaceRoI, BodyRotationNet
  File "E:\OSX\main\..\common\nets\module.py", line 6, in <module>
    from utils.human_models import smpl_x
  File "E:\OSX\main\..\common\utils\human_models.py", line 176, in <module>
    smpl = SMPL()
  File "E:\OSX\main\..\common\utils\human_models.py", line 156, in __init__
    self.layer = {'neutral': smplx.create(cfg.human_model_path, 'smpl', gender='NEUTRAL', **self.layer_arg), 'male': smplx.create(cfg.human_model_path, 'smpl', gender='MALE', **self.layer_arg), 'female': smplx.create(cfg.human_model_path, 'smpl', gender='FEMALE', **self.layer_arg)}
  File "E:\OSX\main\..\common\utils\smplx\smplx\body_models.py", line 2321, in create
    return SMPL(model_path, **kwargs)
  File "E:\OSX\main\..\common\utils\smplx\smplx\body_models.py", line 130, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path E:\OSX\main\..\common\utils\human_model_files\smpl\SMPL_MALE.pkl does not exist!
```
The code seems a tendency to ensure that all gender models are existing...

**Comment by linjing7** [comment]
Hi, I'm sorry that I miss `SMPL_FEMALE.pkl` and `SMPL_MALE.pkl`. Please download them from [here](https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip) and rename `basicModel_f_lbs_10_207_0_v1.0.0.pkl ` to `SMPL_FEMALE.pkl`.

**Comment by eeyrw** [comment]
It works now. SMPL things are really complicated.

**Comment by linjing7** [comment]
Hi, you can modify `neutral` in this [line](https://github.com/IDEA-Research/OSX/blob/e6efdfff2d800390c4ed454ca52c3e3813f458a4/main/OSX.py#L36) into `male` or `female`.

**Comment by eeyrw** [comment]
I see. Thank you.

**Comment by walterhuang23** [comment]
> @eeyrw Hi, you can download the model files by:
> 
> 1. smpl: [SMPL_NEUTRAL.pkl](https://github.com/sampepose/smpl_models/raw/master/SMPL_NEUTRAL.pkl), [SMPL_MALE.pkl and SMPL_FEMALE.pkl](https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.0.0.zip). You need to rename `basicModel_f_lbs_10_207_0_v1.0.0.pkl` and `basicModel_m_lbs_10_207_0_v1.0.0.pkl`  to `SMPL_FEMALE.pkl` and `SMPL_MALE.pkl`.
> 2. smplx: [MANO_SMPLX_vertex_ids.pkl and SMPL-X__FLAME_vertex_ids.npy](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=smplx_mano_flame_correspondences.zip), [SMPLX_NEUTRAL.pkl, SMPLX_NEUTRAL.npz, SMPLX_MALE.npz, SMPLX_FEMALE.npz](https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=SMPLX_NEUTRAL_2020.npz), [SMPLX_to_J14.pkl](https://github.com/vchoutas/expose#preparing-the-data).
> 3. mano: [here](https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip)
> 4. flame:  [flame_dynamic_embedding.npy and flame_static_embedding.pkl](https://github.com/soubhiksanyal/RingNet/tree/master/flame_model), [FLAME_NEUTRAL.pkl](https://download.is.tue.mpg.de/download.php?domain=flame&resume=1&sfile=FLAME2019.zip). You need to rename `generic_model.pkl` to `FLAME_NEUTRAL.pkl`.

While following the steps to prepare the “human_model_files”, I encountered a similar problem on mano downloading as mentioned in this [[issue](https://github.com/hassony2/manopth/issues/5#issuecomment-513452139)](https://github.com/hassony2/manopth/issues/5#issuecomment-513452139).

I attempted to download the file using:

```
wget --no-check-certificate https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip
```

However, the result was a “Download denied” HTML file, which is the same as when I tried accessing the link through the Chrome browser. It seems to require login credentials.

I tried various URLs, such as `https://psfiles.is.tuebingen.mpg.de`, `https://is.tuebingen.mpg.de`, and others, but I was unable to find the correct download link. It appears that `*is.tuebingen*` is not the right way to locate the file.

After several muddling attempts, I discovered that the correct approach is to log in to the site `https://mano.is.tue.mpg.de/download.php` and click on `Models & Code`. This will eventually lead to the target download link: `https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip`.
