### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by sxqhyc** [IDEA-Research/OSX#93]
您好我在运行demo时报这个错误
<img width="1258" alt="29ee70c91709cffb5f1848d0cfbb6ce" src="https://github.com/IDEA-Research/OSX/assets/77818855/9408bb6f-2dec-49c7-a929-dd28d53b4175">

请问该如何解决

**Comment by linjing7** [comment]
你好，我没有遇到这个问题，请参考一下这两个[issue1](https://github.com/HongwenZhang/PyMAF/issues/79), [issue2](https://stackoverflow.com/questions/71196831/container-multi-stage-build-with-pyrender-for-distroless).

**Comment by Hozumi-z** [comment]
我遇到了同样的问题，请问你最后是怎么解决的。

**Comment by sxqhyc** [comment]
@Hozumi-z   我放弃了使用windows，wsl2的自己的电脑，直接去租了台服务器跑的，没再出现这个问题
