### ISSUE TITLE
有些图片重建效果不理想,有什么改进的办法吗？

### ISSUE THREAD

**Issue by APeiZou** [IDEA-Research/OSX#94]
@linjing7  您好，有的图片的重建结果不理想，有什么改进的办法吗？
![render  15](https://github.com/IDEA-Research/OSX/assets/49524647/6627c3b1-9960-4a5c-b1b2-b8e1b960186b)

**Comment by linjing7** [comment]
你好，这些可能是因为训练集不够大导致的，没有遇到过这种情况，可以多加一些训练集或者augmentation，

**Comment by APeiZou** [comment]
好的
