### ISSUE TITLE
Clarify output of loading dataset

### ISSUE THREAD

**Issue by longphamkhac** [IDEA-Research/OSX#96]
Hi, tks for your outstanding job!!! I'm new to 3d human recovery. I'm reading your loading MPII dataset function, can I ask what are the differences between smplx_joint_img and smplx_joint_cam ?

**Comment by linjing7** [comment]
Hi, `smplx_joint_img` is 2D keypoints, `smplx_joint_cam` is 3D keypoints.

**Comment by longphamkhac** [comment]
Another question is that I see in the human_models.py, you changed the joints number of SMPL-X model to 137. However, in the original paper it has only 55 joints include the root. Can you explain why?

**Comment by linjing7** [comment]
Hi, the 137 joints include face keypoints while the 55 joints do not. We add face keypoints for supervision to obtain a better face result.

**Comment by longphamkhac** [comment]
What about 3 more body joints and 10 more hand joints, what are those joints?

**Comment by longphamkhac** [comment]
How do you get the face keypoints in MPII dataset when using SMPL-X model ?

**Comment by linjing7** [comment]
The pseudo GT labels are from [NeuralAnnot](https://github.com/mks0601/NeuralAnnot_RELEASE). You can have a detailed check on that project.
