### ISSUE TITLE
Pyrender seems always utilize CPU

### ISSUE THREAD

**Issue by longphamkhac** [IDEA-Research/OSX#98]
Hi, I try to run OSX model with videos. Despite the fact that setting the environment to be egl (os.environ["PYOPENGL_PLATFORM"] = "egl") but the GPU utilization always equal to 0%, so the rendering step is very slow. Do you have any ideas, thank you so much!!!

**Comment by linjing7** [comment]
Hi, I also found that the GPU utilization of pyrender is low. I think it's a problem of pyrender.

**Comment by longphamkhac** [comment]
Do you have any alternative solutions for rendering mesh in python?

**Comment by linjing7** [comment]
You can try open3d or pytorch3d. Open3d has a very fast rendering speed.

**Comment by longphamkhac** [comment]
Thank you so much, I will try it!!!

**Comment by longphamkhac** [comment]
Sorry to bother you again, when I render to the 3d mesh, I recognize that the overall body shape is a little bit fatter than the actual shape. Do you have any ideas to control the shape parameters because I need to get the body measurement of the person?
